version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: smartpromptiq-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdev123
      POSTGRES_DB: smartpromptiq
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend  # ← make sure this matches your backend folder
    container_name: smartpromptiq-backend
    ports:
      - "3001:5000"
    environment:
      DATABASE_URL: postgres://postgres:localdev123@postgres:5432/smartpromptiq
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: smartpromptiq_postgres_data
