databases:
  - name: smartpromptiq-db
    plan: free # Upgrade to 'starter' or 'standard' for production
    databaseName: smartpromptiq
    user: smartpromptiq

services:
  - type: web
    name: smartpromptiq-api
    plan: free # Upgrade to 'starter' for production
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: smartpromptiq-db
          property: connectionString

  - type: web
    name: smartpromptiq-frontend
    plan: free
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://smartpromptiq-api.onrender.com
